import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import AnimatedPage from "@/components/AnimatedPage";
import { Button, Badge } from "@/components/ui";

/**
 * Home / landing page.
 * Showcases the platform's key features with animated hero section.
 */
export default function Home() {
  return (
    <AnimatedPage className="min-h-screen bg-dark-950 relative overflow-hidden">
      {/* Background orbs */}
      <div className="absolute inset-0 pointer-events-none" aria-hidden="true">
        <motion.div
          className="absolute w-[600px] h-[600px] rounded-full bg-primary-600/10 blur-3xl"
          style={{ top: "-20%", left: "-10%" }}
          animate={{ scale: [1, 1.1, 1], opacity: [0.1, 0.15, 0.1] }}
          transition={{ duration: 10, repeat: Infinity, ease: "easeInOut" }}
        />
        <motion.div
          className="absolute w-[500px] h-[500px] rounded-full bg-violet-600/10 blur-3xl"
          style={{ bottom: "-10%", right: "-5%" }}
          animate={{ scale: [1, 1.08, 1], opacity: [0.1, 0.14, 0.1] }}
          transition={{ duration: 12, repeat: Infinity, ease: "easeInOut", delay: 3 }}
        />
      </div>

      <div className="relative max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Nav */}
        <nav className="flex items-center justify-between py-6">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary-600 to-violet-600 flex items-center justify-center">
              <svg className="w-4 h-4 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" aria-hidden="true">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <span className="font-bold text-slate-100">ResumeAI</span>
          </div>
          <div className="flex items-center gap-3">
            <Link to="/login">
              <Button variant="ghost" size="sm">Sign in</Button>
            </Link>
            <Link to="/signup">
              <Button variant="primary" size="sm">Get started</Button>
            </Link>
          </div>
        </nav>

        {/* Hero */}
        <div className="text-center pt-20 pb-16">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <Badge variant="info" className="mb-6">
              ✨ AI-Powered Resume Analysis
            </Badge>
            <h1 className="text-5xl sm:text-6xl lg:text-7xl font-bold text-slate-100 mb-6 leading-tight">
              Land your dream job with{" "}
              <span className="gradient-text">AI-powered</span>{" "}
              resume insights
            </h1>
            <p className="text-xl text-slate-400 max-w-2xl mx-auto mb-10">
              Upload your resume and job description. Get instant ATS scoring,
              skill gap analysis, and actionable improvement suggestions powered by AI.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/signup">
                <Button variant="primary" size="lg">
                  Analyze my resume free
                </Button>
              </Link>
              <Link to="/login">
                <Button variant="outline" size="lg">
                  Sign in
                </Button>
              </Link>
            </div>
          </motion.div>
        </div>

        {/* Feature grid */}
        <motion.div
          className="grid grid-cols-1 md:grid-cols-3 gap-6 pb-20"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3, duration: 0.6 }}
        >
          {[
            {
              icon: "📊",
              title: "ATS Score",
              desc: "See exactly how your resume scores against ATS systems with a 0–100 compatibility rating.",
            },
            {
              icon: "🎯",
              title: "Skill Gap Analysis",
              desc: "Discover which required and preferred skills are missing from your resume.",
            },
            {
              icon: "🤖",
              title: "AI Suggestions",
              desc: "Get specific, actionable improvement suggestions generated by GPT-4.",
            },
          ].map((f) => (
            <div
              key={f.title}
              className="glass rounded-2xl p-6 hover:border-primary-500/30 transition-colors"
            >
              <div className="text-3xl mb-3">{f.icon}</div>
              <h3 className="font-semibold text-slate-100 mb-2">{f.title}</h3>
              <p className="text-slate-400 text-sm">{f.desc}</p>
            </div>
          ))}
        </motion.div>
      </div>
    </AnimatedPage>
  );
}
